version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: chisme_server
    restart: always
    ports:
      - "4004:4004"
    networks:
      - chisme_network
    environment:
      - APP_ENV=production
    volumes:
      - ./example/data.json:/app/example/data.json
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  chisme_network:
    driver: bridge
